In [ ]:
#https://www.youtube.com/watch?v=gnKbAAVUzro&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK

In [1]:
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [2]:
list1[0]

1

In [3]:
list2 = ['John Elder', 41 , list1, True]
print(list2)

['John Elder', 41, [1, 2, 3, 4, 5], True]


In [7]:
#numpy stands for numeric python
import numpy as np

In [9]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(np1.shape)

(10,)


In [12]:
np2 = np.arange(10)
print(np2)
print(np2.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [13]:
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


In [14]:
#Zeros
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
#Multi dimensional zeros
np5 = np.zeros((2,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
#full
np6 = np.full((10),6)
print(np6)

[6 6 6 6 6 6 6 6 6 6]


In [17]:
#multi dimensional
np7 = np.full((2,10),6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [18]:
#convert python list to np
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)

[1 2 3 4 5]
