In [ ]:
#https://www.youtube.com/watch?v=oIyfZTYQbtk&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&index=6

In [1]:
import numpy as np

In [2]:
#1D
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np1:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [3]:
#2D
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np2:
    #print each row
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [4]:
for x in np2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [5]:
#3D
np3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np3:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
for x in np3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
#easier way : np.nditer()
for x in np.nditer(np3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
