In [1]:
#https://www.youtube.com/watch?v=rN0TREj8G7U&list=PLeo1K3hjS3uv5U-Lmlnucd7gqF-3ehIh0&index=39

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
#numpy array uses less memory, it is fast, and convinient compared to python list
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
import sys

In [9]:
#less memory
#a list with 1000 elements
l = range(1000)
print(sys.getsizeof(5)*len(l))
array= np.arange(1000)
print(array.size*array.itemsize)

28000
8000


In [15]:
#fast
import time
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took:",(time.time()-start)*1000)
#numpy array
start=time.time()
result = a1 + a2
print("numpy list took:",(time.time()-start)*1000)

python list took: 228.79743576049805
numpy list took: 34.37376022338867


In [18]:
#convinient
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a1/a2)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
