In [ ]:
#https://www.youtube.com/watch?v=4LIAHVXnpbY&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&index=3

In [1]:
import numpy as np

In [6]:
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])

In [3]:
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#square route of each element
print(np.sqrt(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [7]:
#absolute value
print(np.absolute(np1))

[3 2 1 0 1 2 3 4 5 6 7 8 9]


In [8]:
#exponents
print(np.exp(np1))

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [10]:
#min/max
print(np.max(np1))
print(np.min(np1))

9
-3


In [11]:
#sign positive or negative
print(np.sign(np1))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


In [14]:
#trig sin cos log
print(np.sin(np1))
#print(np.log(np1)) #throws errors for some vals

[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]


In [ ]:
#search for numpy universal functions
#https://numpy.org/doc/stable/reference/ufuncs.html