In [1]:
import numpy as np

In [6]:
#search
np1 = np.array([1,2,3,4,5,6,7,8,9,10,3])

x = np.where(np1 == 3)
print(np1)
print(x)
print(x[0])
print(np1[x[0]])

[ 1  2  3  4  5  6  7  8  9 10  3]
(array([ 2, 10]),)
[ 2 10]
[3 3]


In [9]:
#return even items
y = np.where(np1 % 2 == 0)
print(np1)
print(y[0])

[ 1  2  3  4  5  6  7  8  9 10  3]
[1 3 5 7 9]


In [11]:
#return odd items
z = np.where(np1 % 2 == 1)
print(np1)
print(z[0])

[ 1  2  3  4  5  6  7  8  9 10  3]
[ 0  2  4  6  8 10]
