In [ ]:
#https://www.youtube.com/watch?v=PbKOrSottRQ&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&index=2

In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
#slice containing 2,3,4,5
print(np1[1:5])

[2 3 4 5]


In [4]:
#return from something till the end
print(np1[3:])

[4 5 6 7 8 9]


In [5]:
print(np1[-3:-1])

[7 8]


In [6]:
print(np1[1:5])
print(np1[1:5:2])

[2 3 4 5]
[2 4]


In [7]:
print(np1[::2])

[1 3 5 7 9]


In [8]:
print(np1[::3])

[1 4 7]


In [9]:
#slice a 2d array
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
#pull out a single item
print(np2[1,2])

8


In [10]:
print(np2[0:1,1:3])

[[2 3]]


In [11]:
print(np2[0:2,1:3])

[[2 3]
 [7 8]]
