In [ ]:
#https://www.youtube.com/watch?v=_d_Ka-ks2a0&list=PLeo1K3hjS3uv5U-Lmlnucd7gqF-3ehIh0&index=41

In [1]:
import numpy as np

In [2]:
n = [6,7,8]
n[0:2]

[6, 7]

In [3]:
n[-1]

8

In [4]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [5]:
a[-1]

8

In [7]:
#multi dimensional array
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [8]:
a[1,2]

3

In [9]:
a[0:2,2]

array([8, 3])

In [10]:
a[-1]

array([9, 3, 2])

In [11]:
a[-1,0:2]

array([9, 3])

In [12]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [14]:
#multi dimensional array
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [15]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [16]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [18]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
#vertical stacking
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
#horizontal stacking
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [24]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [27]:
result = np.hsplit(a,3)

In [28]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [29]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [30]:
result = np.vsplit(a,2)

In [31]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [32]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
b = a > 4

In [34]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [37]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])